title: Beginning of something bigger than an ant
author: GitHub User SkyW4lk3r919
email: yasin.sengoez@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
You found me. This is my GitHub Page and I will make sth cool

# social links

github_username:  SkyW4lk3r919

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
